<?php

/**
 * Implemetnación del hoock help
 */
function ranking_help() {
	$output = '';
	switch($path){
		case 'admin/help#ranking':
			$output = '<p>'.t("Permite manejar y controlar el ránking de las modalidades.").'</p>';
			break;
	}
	return $output;
}
/**
* Implementation of hook_perm()
* Outlines permissions for this module.
* @return array - An array of valid permissions for the match module
*/
function ranking_perm(){
  return array('administer point table', 'view ranking');
}//end function match_perm()
/**
 * Implementation of hook_menu()
 * Admin menu link for the module
 * @return unknown_type
 */

function ranking_menu(){
  $items[ 'admin/base_datos_externa/ranking' ] = array (
    'title' => 'Ranking',
    'page callback' => 'drupal_get_form',
	'page arguments' => array( 'ranking_admin' ),
	'access arguments' => array( 'administer point table' ),	
	'type' => MENU_LOCAL_TASK,
  );
  $items[ 'admin/base_datos_externa/ranking/desafios' ] = array (
    'title' => 'Desafios',
    'page callback' => 'drupal_get_form',
	'page arguments' => array( 'ranking_desafios' ),
	'access arguments' => array( 'administer point table' ),
    'file' => 'inc/ranking_desafios.inc',
	'type' => MENU_LOCAL_TASK,
  );
  $items[ 'admin/base_datos_externa/ranking/torneos' ] = array (
    'title' => 'Torneos',
    'page callback' => 'drupal_get_form',
	'page arguments' => array( 'ranking_torneos' ),
	'access arguments' => array( 'administer point table' ),
    'file' => 'inc/ranking_torneos.inc',
	'type' => MENU_LOCAL_TASK,
  );
	
	
	//MENÚ para mostrar el ranking
  $items[ 'taxonomy/term/%/ranking' ] = array (
	'title' => t( 'Puntuacion' ),
    'page callback' => 'drupal_get_form',
	'page arguments' => array( 'mostrar_puntuacion' ),
	'access arguments' => array( 'view ranking' ),
    //'file' => 'inc/ranking_torneos.inc',
	'type' => MENU_LOCAL_TASK,
  );

  return $items;
}
/**
 * Función para desplegar la forma de bienvenida para el módulo ránking
 * no estoy seguro de que se despliegue, pero si se despliega sólo
 * debe mostrar una leyenda indicando la forma de proceder con la
 * configuración de cada tipo de ránking.
 */
function ranking_admin() {
    $form['leyenda'] = array (
        '#value' => '<p>Bienvenido a la seccion de administracion de ranking.</p>.<p>Para configurar dirígete a:</p>'
    );
    $form['desafios'] = array (
        '#value' => l(t('Configuracion para desafios'), 'admin/base_datos_externa/ranking/desafios'),
    );
    $form['torneos'] = array (
        '#value' => l(t('Configuracion para torneos'), 'admin/base_datos_externa/ranking/torneos'),
    );
}
/**
 * Implementación del hoock theme
 */
function ranking_theme() {
    return array (
        'ranking_desafios' => array (
            'arguments' => array ('form' => NULL),
            'file' => '/theme/ranking_desafios.inc',
        ),
        'ranking_torneos' => array (
            'arguments' => array ('form' => NULL),
            'file' => '/theme/ranking_torneos.inc',
        ),
    );
}
/**
 *	Función para mostrar la puntuación de una modalidad
 */
function mostrar_puntuacion(  )
{
	
	dsm( "Hola" );
	
	$id_Modalidad_Juego_Temporada = arg( 2 );
	
	
	$form[ 'puntuacion' ] = array
	(
		'#title' => t( 'Puntuacion.' ),
		'#type' => 'fieldset',
		//'#default_value' => $Equipos->Nombre,
		//'#options' => $options,
		'#collapsible' => 0,
	);
	
	db_set_active( 'eSM' );
	
		$Puntuacion_result = db_query( "SELECT { * } FROM { Puntuacion } AS { p } INNER JOIN { Equipo } AS { e } ON { p.nid_Equipo } = { e.nid_Equipo } INNER JOIN { Modalidad_Juego_Temporada } AS { m } ON { e.id_Modalidad_Juego_Temporada } = { m.id_Modalidad_Juego_Temporada } WHERE { p.nid_Equipo } = %d ", arg( 2 ) );
		
	db_set_active( 'default' );	
	
	//Primero mostraremos todos los equipos
	while( $Puntuacion = db_fetch_object( $Puntuacion_result ) )
	{
		
		
		$form[ 'puntuacion' ][ 'equipos' ] = array
		(
			'#title' => t( 'Equipos' ),
			'#type' => 'fieldset',
			'collapsible' => 1,
		);
		
		db_set_active( 'eSM' );
		
			$Equipo_result = db_query( "SELECT { * } FROM Equipo WHERE { Equipo.nid_Equipo } = %d", $Puntuacion->nid_Equipo );
		
		db_set_active( 'default' );
		
		
		$Equipo = db_fetch_object( $Equipo_result );
		
		$form[ 'puntuacion' ][ 'equipos' ][ 'Abreviacion' ] = array (
			'#title' => 'Abreviacion',
			'#type' => 'item',
			'#value' => $Equipo->Abreviacion
			
		);
		
		$form[ 'puntuacion' ][ 'equipos' ][ 'Puntuacion' ] = array (
			'#title' => 'Puntuacion',
			'#type' => 'item',
			'#value' => $Puntuacion->Puntuacion
			
		);
		

		$form[ 'puntuacion' ][ 'equipos' ][ 'PJ' ] = array (
			'#title' => 'Desafios Jugados',
			'#type' => 'item',
			'#value' => $Puntuacion->PJ
			
		);

		$form[ 'puntuacion' ][ 'equipos' ][ 'PG' ] = array (
			'#title' => 'Desafíos Ganados',
			'#type' => 'item',
			'#value' => $Puntuacion->PG
			
		);

		$form[ 'puntuacion' ][ 'equipos' ][ 'Racha' ] = array (
			'#title' => 'Desafíos Ganados',
			'#type' => 'item',
			'#value' => $Puntuacion->Racha
			
		);
		
		
		
	}
	
	return $form;
}
/**
 * Función para actualizar el ranking de un equipo
 * Recibe el nind_Equipo, Puntación a sumar, Win (1) /Loss (0)
 * La variable torneo indica si la actualización es por torneo y el valor es 0 por defecto (No es torneo)
 * La variable win indica si ganó o perdió el desafío y el valor por defecto es 0 (Perdió el desafío)
 */
function actualizar_ranking($nid_Equipo, $puntos, $torneo = 0, $win = 0) {
    db_set_active('eSM');
        $puntuacion = db_fetch_object(db_query('SELECT * FROM {Puntuacion} WHERE nid_Equipo = %d', $nid_Equipo));
    db_set_active('default');
    
    $puntuacion->Puntuacion = $puntuacion->Puntuacion + $puntos;    //Actualiza los puntos del equipo
    
    if ($torneo == 0) {         //El partido es un desafío, hace la actualización de puntos y partidos jugados
        ++$puntuacion->PJ;      //Suma otro partido a los partidos jugados por el equipo
        
        if($puntuacion->Puntuacion < 0)     //Asegura que la puntuación nunca vaya a bajar de cero.
            $puntuacion->Puntuacion = 0;
        
        if ($win == 0) {        //El equipo perdió el partido
            if ($puntuacion >= 0) {
                watchdog('ranking', 'Ha ocurrido un error al calcular los puntos del partido : '. $nid_Equipo, NULL, WATCHDOG_ERROR);
                return;
            }
            
            if($puntuacion->Racha > 0)
                $puntuacion->Racha == 0;        //Resetea la racha a cero
        }
        else {
            if ($puntuacion <= 0) {
                watchdog('ranking', 'Ha ocurrido un error al calcular los puntos del partido : '. $nid_Equipo, NULL, WATCHDOG_ERROR);
                return;
            }
            
            ++$puntuacion->PG;      //Incrementa el número de partidos ganados
            ++$puntuacion->Racha;   //Incrementa la racha del jugador
        }
    }
    else {
        if ($puntos < 0 ) {
            watchdog('ranking', 'Ha ocurrido un error al calcular los puntos del partido : '. $nid_Equipo, NULL, WATCHDOG_ERROR);
            return;
        }
        ++$puntuacion->TJ;
        if ($win == 1)
            ++$puntuacion->TG;
    }
    
    db_set_active('eSM');
        db_query('UPDATE {Puntuacion} SET Puntuacion = %d, PJ = %d, PG = %d, Racha = %d, TJ = %d, TG = %d WHERE nid_Equipo = %d', $puntuacion->Puntuacion, $puntuacion->PJ, $puntuacion->PG, $puntuacion->Racha, $puntuacion->TJ, $puntuacion->TG, $nid_Equipo);
    db_set_active('default');
    
    return;
}