<?php

/**
 * Implemetnación del hoock help
 */
function ranking_help() {
	$output = '';
	switch($path){
		case 'admin/help#ranking':
			$output = '<p>'.t("Permite manejar y controlar el ránking de las modalidades.").'</p>';
			break;
	}
	return $output;
}
/**
* Implementation of hook_perm()
* Outlines permissions for this module.
* @return array - An array of valid permissions for the match module
*/
function ranking_perm(){
  return array('administer point table', 'view ranking');
}//end function match_perm()
/**
 * Implementation of hook_menu()
 * Admin menu link for the module
 * @return unknown_type
 */

function ranking_menu(){
  $items[ 'admin/base_datos_externa/ranking' ] = array (
    'title' => 'Ranking',
    'page callback' => 'drupal_get_form',
	'page arguments' => array( 'ranking_admin' ),
	'access arguments' => array( 'administer point table' ),	
	'type' => MENU_LOCAL_TASK,
  );
  $items[ 'admin/base_datos_externa/ranking/desafios' ] = array (
    'title' => 'Desafios',
    'page callback' => 'drupal_get_form',
	'page arguments' => array( 'ranking_desafios' ),
	'access arguments' => array( 'administer point table' ),
    'file' => 'inc/ranking_desafios.inc',
	'type' => MENU_LOCAL_TASK,
  );
  $items[ 'admin/base_datos_externa/ranking/torneos' ] = array (
    'title' => 'Torneos',
    'page callback' => 'drupal_get_form',
	'page arguments' => array( 'ranking_torneos' ),
	'access arguments' => array( 'administer point table' ),
    'file' => 'inc/ranking_torneos.inc',
	'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}
/**
 * Función para desplegar la forma de bienvenida para el módulo ránking
 * no estoy seguro de que se despliegue, pero si se despliega sólo
 * debe mostrar una leyenda indicando la forma de proceder con la
 * configuración de cada tipo de ránking.
 */
function ranking_admin() {
    $form['leyenda'] = array (
        '#value' => '<p>Bienvenido a la seccion de administracion de ranking.</p>.<p>Para configurar dirígete a:</p>'
    );
    $form['desafios'] = array (
        '#value' => l(t('Configuracion para desafios'), 'admin/base_datos_externa/ranking/desafios'),
    );
    $form['torneos'] = array (
        '#value' => l(t('Configuracion para torneos'), 'admin/base_datos_externa/ranking/torneos'),
    );
}