SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `eSM` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;

USE `eSM`;

CREATE  TABLE IF NOT EXISTS `eSM`.`Disponibilidad_Horas` (
  `id_Agente_Libre` INT(11) NOT NULL ,
  `Morning` TINYINT(4) NOT NULL DEFAULT 0 ,
  `Evening` TINYINT(4) NOT NULL DEFAULT 0 ,
  `Night` TINYINT(4) NULL DEFAULT 0 ,
  PRIMARY KEY (`id_Agente_Libre`) ,
  UNIQUE INDEX `id_Agente_Libre_UNIQUE` (`id_Agente_Libre` ASC) ,
  INDEX `id_Agente_Libre_Horas` (`id_Agente_Libre` ASC) ,
  CONSTRAINT `id_Agente_Libre_Horas`
    FOREIGN KEY (`id_Agente_Libre` )
    REFERENCES `eSM`.`Agente_Libre` (`id_Agente_Libre` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

ALTER TABLE `eSM`.`Disponibilidad` ADD COLUMN `Domingo` TINYINT(4) NOT NULL DEFAULT 0  AFTER `Martes` , ADD COLUMN `Jueves` TINYINT(4) NOT NULL DEFAULT 0  AFTER `Martes` , ADD COLUMN `Miercoles` TINYINT(4) NOT NULL DEFAULT 0  AFTER `Martes` , ADD COLUMN `Sabado` TINYINT(4) NOT NULL DEFAULT 0  AFTER `Jueves` , ADD COLUMN `Viernes` TINYINT(4) NOT NULL DEFAULT 0  AFTER `Jueves` , CHANGE COLUMN `Fecha_Inicio` `Lunes` TINYINT(4) NOT NULL DEFAULT 0  , CHANGE COLUMN `Fecha_Fin` `Martes` TINYINT(4) NOT NULL DEFAULT 0  
, DROP INDEX `Fechas_Disponibles_UNIQUE` 
, DROP INDEX `Fecha_Fin_UNIQUE` , RENAME TO  `eSM`.`Disponibilidad_Dias` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
