SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `eSM`.`Integrantes_Equipo` 
DROP INDEX `Estado_UNIQUE` 
, DROP PRIMARY KEY ;

ALTER TABLE `eSM`.`Agente_Libre` DROP FOREIGN KEY `fk_Agente_Libre_Jugador` ;

ALTER TABLE `eSM`.`Agente_Libre` 
  ADD CONSTRAINT `fk_Agente_Libre_Jugador`
  FOREIGN KEY (`id_Jugador` )
  REFERENCES `eSM`.`Jugador` (`id_Jugador` )
  ON DELETE NO ACTION
  ON UPDATE CASCADE;

ALTER TABLE `eSM`.`Disponibilidad_Horas` DROP FOREIGN KEY `fk_Disponibilidad_Horas_Agente_Libre` ;

ALTER TABLE `eSM`.`Disponibilidad_Horas` 
  ADD CONSTRAINT `fk_Disponibilidad_Horas_Agente_Libre`
  FOREIGN KEY (`id_Jugador` )
  REFERENCES `eSM`.`Agente_Libre` (`id_Jugador` )
  ON DELETE NO ACTION
  ON UPDATE CASCADE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
